### ISSUE TITLE
如何下载mp3格式？

### ISSUE THREAD

**Issue by pcbcos** [greats3an/pyncm#1]
我注意到似乎下载的格式均为m4a或flac，那么如何下载mp3呢

**Comment by greats3an** [comment]
EAPI所提供的音频文件大多数为m4a (ALAC) 和 FLAC 格式
但也有入库较早的部分专辑（如：[Beyond XRCD Special](https://music.163.com/#/album?id=34113) ）
会在**标准**音质下提供 MP3 格式的音频文件。若希望下载 MP3 格式，可在执行时附加`--quality standard`
因 ALAC 在文件大小及音质上较 MP3 的优越性，较新的歌曲在标准格式下也会采用这种格式
若一定要使用 MP3 格式，推荐使用 [ffmpeg](https://www.ffmpeg.org/)进行转码
用 Python 实现这方面的东西有些臃肿了😅

**Comment by Binaryify** [comment]
https://interface3.music.163.com/eapi/song/enhance/player/url
这个接口可以传入br参数控制返回的音频的质量，如320000
