### ISSUE TITLE
作者厉害，这个问题我还没有找到解决方法，Worker exception:[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by gitQqqHs** [greats3an/pyncm#10]
if __name__ == '__main__':
	ncm_helper = nutils.helper.NcmHelper(output=r"E:\CloudMusic\output", reporter=sys.stdout.write)
	ncm_helper.DownloadAllTracksInPlaylistAndMerge(id=779016853, folder=r"E:\CloudMusic\output" )
代码运行后出现的问题，这个我还没有找到解决方法

**Supported audio file for E:\CloudMusic\output\1325898067 is missing,Cannot continue formatting!
Supported audio file for E:\CloudMusic\output\1329713104 is missing,Cannot continue formatting!
Supported audio file for E:\CloudMusic\output\1331819040 is missing,Cannot continue formatting!
Supported audio file for E:\CloudMusic\output\1361193752 is missing,Cannot continue formatting!
Error while getting track attribute TrackPublishTime,using fallback value None
Supported audio file for E:\CloudMusic\output\26289183 is missing,Cannot continue formatting!
Supported audio file for E:\CloudMusic\output\28652821 is missing,Cannot continue formatting!
Worker exception:[Errno 2] No such file or directory: "E:\\CloudMusic\\output\\4 Non Blondes - What's Up？.lrc\\lyrics.json"
Supported audio file for E:\CloudMusic\output\471754946 is missing,Cannot continue formatting!
Supported audio file for E:\CloudMusic\output\514235010 is missing,Cannot continue formatting!
Supported audio file for E:\CloudMusic\output\5268162 is missing,Cannot continue formatting!
Supported audio file for E:\CloudMusic\output\573240010 is missing,Cannot continue formatting!
Worker exception:[Errno 2] No such file or directory: 'E:\\CloudMusic\\output\\Achim Reichel - Aloha Heja He.lrc\\lyrics.json'
Worker exception:[Errno 2] No such file or directory: 'E:\\CloudMusic\\output\\AC／DC - Dirty Deeds Done Dirt Cheap.lrc\\lyrics.json'
Worker exception:[Errno 2] No such file or directory: 'E:\\CloudMusic\\output\\Adele - Skyfall (Full Length).lrc\\lyrics.json'
Worker exception:[Errno 2] No such file or directory: 'E:\\CloudMusic\\output\\Adele - Someone Like You.lrc\\lyrics.json'
Worker exception:[Errno 2] No such file or directory: 'E:\\CloudMusic\\output\\Adele - When We Were Young.lrc\\lyrics.json'
Worker exception:[Errno 2] No such file or directory: 'E:\\CloudMusic\\output\\Alborada Del Inka - The Last Mohican.lrc\\lyrics.json'
Worker exception:[Errno 2] No such file or directory: 'E:\\CloudMusic\\output\\Alison Krauss - When You Say Nothing At All.lrc\\lyrics.json'
Worker exception:[Errno 2] No such file or directory: 'E:\\CloudMusic\\output\\Amy Winehouse - Love Is A Losing Game.lrc\\lyrics.json'
Worker exception:[Errno 2] No such file or directory: 'E:\\CloudMusic\\output\\Andy Williams - Where Do I Begin.lrc\\lyrics.json'
Worker exception:[Errno 2] No such file or directory: 'E:\\CloudMusic\\output\\Anna F - Too Far.lrc\\lyrics.json'**

**Comment by greats3an** [comment]
1. 日志中报错的歌曲都需要**开通VIP畅听**，即需要VIP账户登录；登录API如下
`ncm_helper.Login('<手机号>','<密码>')`；登录状态将持续至该`NcmHelper`被删除
2. 且 `ncm_helper.DownloadAllTracksInPlaylistAndMerge` 不需要指定 `folder`，留空即可

不过`NcmHelper`类的API并没打算给`__main__.py`之外的模块用，`os.system`配合命令行`python -m pyncm`可能会更方便些。
没有VIP账户可以参考下[pyncmd](https://github.com/greats3an/pyncmd)的HTTP API，目前[demo站](https://mos9527.tooo.top/ncm)仍在线

**Comment by gitQqqHs** [comment]
我之前也用过命令行  os.system配合命令行python -m pyncm
不过下载歌单列表时出错，所以才研究的代码，好在代码可以下载歌单，一个歌单200首

**Comment by greats3an** [comment]
用这个命令试了下 `python -m pyncm playlist --id 779016853`
出错的歌曲（如[桂河桥进行曲](https://music.163.com/#/song?id=5268162)) 在网易云也无法播放（版权问题？）
但这样也把能听的都下载了，毕竟命令行实现也就是这样写的

方便的话能贴下命令行日志吗😅，记得要登陆
