### ISSUE TITLE
DumpSessionAsString & LoadSessionFromString 错误

### ISSUE THREAD

**Issue by aynakeya** [greats3an/pyncm#15]
具体如下
首次登录
```
rsp = login.LoginQrcodeCheck(self.uuid)
        if rsp['code'] == 803 or rsp['code'] == 800:
            login.WriteLoginInfo(login.GetCurrentLoginStatus())
```
这个时候调用`cloudsearch.GetSearchResult() ` 返回正常的结果

但是如果再次登录的时候使用session
```
SetCurrentSession(LoadSessionFromString(DumpSessionAsString(GetCurrentSession())))
```
`cloudsearch.GetSearchResult() ` 会返回一个加密的response

```
{'result': '35b1748964a......3580c7d96ead6d0236e54a94', 'code': 200, 'abroad': True}
```

所以这个扫码登录是正常的，但是通过LoadSessionFromString来登录就不正常了。猜测可能是多了一个验证的参数？

**Comment by greats3an** [comment]
我这里只能在挂美国梯子后重现这里的问题，也许是针对海外 IP 才有这种情况？

刚花了点时间把[result 加密](https://github.com/greats3an/pyncm/blob/bd566c5023074861b0eae64bc180782ecc841f30/pyncm/utils/security.py)做了下，海外IP也应该可以直接使用这里出问题的API了

其次还可以加header试试看，不过还是建议用pip把包更新一下:
`GetCurrentSession().headers['X-Real-IP'] = '118.88.88.88'`

**Comment by aynakeya** [comment]
可以了，谢谢
