### ISSUE TITLE
关于python3.8中海象运算符特性

### ISSUE THREAD

**Issue by liuyunfz** [greats3an/pyncm#2]
您好，在您的MD文档中标明了适配python3.x，但当我clone运行后却发生报错，经过查阅是ncm_core.py第308行中的:=，这是python3.8新加的特性，我本人的python也刚好只是3.7，所以就导致了这个问题，希望能尽快得到修复或修改相关文档。如果不是这个原因造成的错误，也还请指出，以下是我的出错详情。

Traceback (most recent call last):
  File "d:/github/pyncm/cs.py", line 1, in <module>
    from ncm.ncm_core import NeteaseCloudMusic
  File "d:\github\pyncm\ncm\ncm_core.py", line 308
    self.log(','.join((cookie:= self.session.cookies.get_dict()).keys()), format=strings.DEBUG_UPDATED_COOKIE)
                             ^
SyntaxError: invalid syntax

**Comment by greats3an** [comment]
确实没注意，已经把 [PEP 572](https://www.python.org/dev/peps/pep-0572/) 有关的代码重构了，[见 Commit](https://github.com/greats3an/pyncm/commit/3ff09b6b065265e169a4340551a0703e31e13bd1)

**Comment by greats3an** [comment]
已测试在 Python 3.7.3 可用，抱歉没能早些说明😅
