### ISSUE TITLE
[问题] AAC格式的歌曲例子

### ISSUE THREAD

**Issue by tuxzz** [greats3an/pyncm#8]
看到`/eapi/song/enhance/player/url`的封装函数中默认使用的格式是aac，然而我抓了一些歌没有发现使用MP3以外的格式的例子。
可以给出一些使用MP3以外格式的例子吗？

**Comment by greats3an** [comment]
`encodeType` 较 `br` 参数优先级低，且新的网易客户端已废弃该参数 (包括 `quality`) —— 已在[此commit](https://github.com/greats3an/pyncm/commit/c9669a06aff57c16afa74bbeef65c94223c7def9)中跟进

现改变格式应通过改变`bitrate`，即比特率

可参考 [singletrack.py](https://github.com/greats3an/pyncm/blob/master/demos/track/singletrack.py)（需登录）
